name: psa_tap
channels:
  - astropy
  - conda-forge
dependencies:
  - python=3
  - numpy
  - matplotlib
  - pandas
  - astropy
  - astroquery
  - pvl
  - pillow
  - pip
  - scikit-image
  - pip:
    - pds4_tools


